---
services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    container_name: whoami
    image: traefik/whoami:latest
    labels:
      traefik.enable: true
      # Route d'exemple whoami sur domaine dynamique sslip.io
      traefik.http.routers.whoami.rule: Host(`whoami.127.0.0.1.sslip.io`)
      traefik.http.routers.whoami.middlewares: tinyauth
      traefik.http.services.whoami.loadbalancer.server.port: 80

  tinyauth-frontend:
    container_name: tinyauth-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - 5173:5173
    labels:
      traefik.enable: true
      # UI accessible via tinyauth.127.0.0.1.sslip.io
      traefik.http.routers.tinyauth-frontend.rule: Host(`tinyauth.127.0.0.1.sslip.io`)

  tinyauth-backend:
    container_name: tinyauth-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - ./internal:/tinyauth/internal
      - ./cmd:/tinyauth/cmd
      - ./main.go:/tinyauth/main.go
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
      - 4000:4000
    labels:
      traefik.enable: true
      # Middleware d'auth (forwardAuth)
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth-backend:3000/api/auth/traefik
      # Route backend directe (API) sur api.127.0.0.1.sslip.io si besoin d'accès direct
      traefik.http.routers.tinyauth-backend.rule: Host(`api.127.0.0.1.sslip.io`)
